x-env: &env
  MONGO_HOST: ${MONGO_HOST:-mongo}
  MONGO_PORT: ${MONGO_PORT:-27017}
  MONGO_USER: ${MONGO_USER:-admin}
  MONGO_PASS: ${MONGO_PASS:-admin}
  MONGO_NAME: ${MONGO_NAME:-bot}
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-admin}

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis:/data
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      <<: *env
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
  redis:
