# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  create:
    tags:
      - "*"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clojars:
    runs-on: ubuntu-latest

    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2

      - uses: jlesquembre/clojars-publish-action@0.3
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
          USE_GIT_REF: false
